---
title: educational blogging
timezone: Europe/Copenhagen
collections:
  capitulos:
    title: Capitulos
    output: true
    permalink: "/:path/"
  mil1-dot-1:
    title: MIL1.1
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: capitulos
  values:
    layout: capitulo
tagline: et praktisk forsøg på at blogge sig igennem MIL
url: http://alexanderrae.github.io
paginate: 1
baseurl: "/"
sass:
  sass_dir: _sass
  style: compressed
author:
  name: Alexander Råe
  url: https://alexanderrae.github.io
  email: chri0a77@gmail.com
version: 1.0.0
github:
  repo: https://github.com/alexanderrae/alexanderrae.github.io
